baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "muyang's blog"
theme = 'hugo-theme-void'
 

# Social media links
[params]
  [params.social]
    github = "https://github.com/cmuyang"
    twitter = "https://twitter.com/yourusername"
    email = "cyj1009@stu.ouc.edu.cn"
  [params.avatar]
    url = "image.png"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

# Table of Contents (recommended)
[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

# Allow raw HTML within Markdown (for KaTeX, etc.)
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true